#!/bin/bash
# SynCoin - Quick Start
echo "🌱 SynCoin — Universal Decarbonized AI Compute Mesh"
echo "==================================================="
echo ""
echo "1. Start P2P Hub Node (WebSocket port 8766):"
echo "   python3 syncoin_node.py"
echo ""
echo "2. Start OpenAI-Compatible Inference Gateway (Port 8767):"
echo "   python3 syncoin_gateway.py"
echo ""
echo "3. Start Desktop GUI Client:"
echo "   cd desktop && python3 desktop_app.py"
echo ""
echo "🌱 100% Free & Open-Source (MIT License) — Built for all of humanity."
